### ISSUE TITLE
Use 'answered' verb for interactions

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#14]
When converting SCORM to Tin Can, SCORM cloud uses the verb http://adlnet.gov/expapi/verbs/answered for interactions, rather than passed/failed as indicated in this document. The result success property indicates whether or not the interaction was successfully answered. 

This approach has a lot of adoption as it's what recommended here: http://tincanapi.com/scorm-to-tin-can-api-cookbook/ and here: http://www.tincanapi.co.uk/pages/SCORM_to_Tin_Can_API.html#Part_3_-_Summary_of_When_to_Send_Tin_Can_API_Statements both of which have been around and followed for a while.

**Comment by creighton** [comment]
Since we are mapping .learner_response, we feel the responded verb is a better fit. The 3.2 verb table was updated to use 'responded' for interactions and the description was updated.
