### ISSUE TITLE
Use of result

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#17]
I'd like to see more use of result in the various events, for example in the passed/failed statement. 

On completion, what scenario might the AP want to set completion by result only and not verb? The example given is a statement with the verb passed, but the paragraph above explains that if the course is passed, then it's assumed to be completed anyway. 

I'd like to see the result completion and success properties used to reinforce the meaning of the verb for the sake of reporting tools that don't explicitly recognize this profile. This has generally been the approach of people doing SCORM-ish stuff to date. See for example http://tincanapi.com/scorm-to-tin-can-api-cookbook/

**Comment by creighton** [comment]
see https://github.com/adlnet/xAPI-SCORM-Profile/pull/30

result is now used with a 'terminated' statement to indicate SCO status. Statements are still permitted to be stored about the SCO, such as 'passed' and 'completed' (all which could have a result), but these are not required for status determination. This was mainly decided for ease of queries. Reporting tools can now say give me all 'terminated' statements (with or without course or SCO IRIs) and then look at the result property for final status of that activity.
