### ISSUE TITLE
Allow 'passed' and 'failed' to include score

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#21]
https://github.com/adlnet/xAPI-SCORM-Profile/blob/master/xapi-scorm-profile.md#set-a-score-for-the-course

Common practice is to include a score with the completed, passed and/or failed statement rather than issuing a separate 'scored' statement. I had assumed that the scored statement was envisaged to be used in situations when a score needed to be communicated without implying anything else. 

I'd like to see it explicitly stated that score can be passed with completed, passed and failed and that scored is optional.

**Comment by creighton** [comment]
see https://github.com/adlnet/xAPI-SCORM-Profile/pull/30   

If this issue still needs addressed let me know and I'll take care of it.

**Comment by garemoko** [comment]
I'd add a link in https://github.com/creighton/xAPI-SCORM-Profile/blob/master/xapi-scorm-profile.md#score to https://github.com/adlnet/xAPI-SCORM-Profile/blob/master/xapi-scorm-profile.md#shorthand-for-passed-the-course-with-a-score-and-completion-value

**Comment by creighton** [comment]
link added in score to point to terminating an attempt https://github.com/creighton/xAPI-SCORM-Profile/blob/dev/xapi-scorm-profile.md#terminating-an-attempt
