### ISSUE TITLE
Add more example JSON in the appendix

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#23]
From https://github.com/adlnet/xAPI-SCORM-Profile/blob/master/xapi-scorm-profile.md#comments-from-lms onwards the examples get thinner on the ground. 

The examples above are really really helpful and I'd appreciate an example for every entry in the appendix.

**Comment by creighton** [comment]
Some data model elements are properties of state or profile JSON objects. I tried to make that clearer and add examples for querying to get that information. 

If this isn't sufficient let me know and I'll try to add some more examples

**Comment by garemoko** [comment]
Closing this issue. I'll review the whole doc again at some point in the future and if I still feel it's light on examples at the end I'll open a new one.
