### ISSUE TITLE
Use 'attempted' to indicate the start of a new attempt

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-SCORM-Profile#26]
We should use the verb http://adlnet.gov/expapi/verbs/attempted to indicate the start of a new attempt alongside the verbs that indicate the start of a new session.

**Comment by creighton** [comment]
I rewrote section 5.0. It doesn't include 'attempted' but does outline the scorm temporal model. In a nutshell, verbs initialized/terminated begin and end an attempt; verbs suspended/resumed suspend the attempt. 

https://github.com/adlnet/xAPI-SCORM-Profile/pull/30

**Comment by garemoko** [comment]
That's a big difference to CMI5's use of initialized and terminated to mark the start and end of a session. Would be good to get these two overlapping draft specifications merged asap.

**Comment by creighton** [comment]
https://github.com/AICC/CMI-5_Spec_Current/blob/master/cmi5_runtime.md#722-first-statement-api-call

https://github.com/AICC/CMI-5_Spec_Current/blob/master/cmi5_runtime.md#93-verbs

Looking at that, it seems that this profile and CMI5 are very close. I think the only issue is that CMI5 is using http://www.aicc.org/cmi5/verbs, whereas this uses http://adlnet.gov/expapi/verbs.

**Comment by creighton** [comment]
nope i see some differences now that i've had a chance to look at it more.. thanks for bringing it up

**Comment by creighton** [comment]
CMI5 has changed and doesn't look to use attempted any more. Additionally they have switched to use the ADL verbs. I don't think a change to this doc is needed.
