### ISSUE TITLE
Setting a activity to incomplete

### ISSUE THREAD

**Issue by jonopoltrack** [adlnet/xAPI-SCORM-Profile#27]
SCORM 2004 4th Ed has implied behavior when a SCO terminates without setting any data model elements (it is completed and passed).  Marking an activity explicitly as incomplete is needed. Need the ability to leave an activity with an incomplete status.

Result with completion=false could be used.  With initialize? completed?  terminated? verbs...

**Comment by creighton** [comment]
Changed doc to use "terminated" statement with result for status. This allows us to use "terminated" with completion=false for "incomplete"

https://github.com/adlnet/xAPI-SCORM-Profile/pull/30
