### ISSUE TITLE
Parent context activities

### ISSUE THREAD

**Issue by jonopoltrack** [adlnet/xAPI-SCORM-Profile#28]
When considering a legacy SCORM course that has several nested levels of SCOs. 
Ex.
Course ABC
  - Introduction
  - Lesson 1
      - Module 1
      - Module 2
          - Chapter 1
          - Chapter 2
          - Chapter 3
      - Module 3
  - Lesson 2
  - Lesson 3
      - Quiz
  - Summary
  
What should Chapter 2's (under Lesson 1 module 2) parent context activity be?  Course ABC? Module 2?  Or multiple Module 2, Lesson 1 AND Course ABC

**Comment by garemoko** [comment]
Module 2 - lesson and course should be groupings.

**Comment by creighton** [comment]
Doc changed to use contextActivities grouping for most cases. Parent is only used when it is clear there is an immediate parent of an activity, such as a SCO for an assessment activity (or SCO for an interaction activity).

https://github.com/adlnet/xAPI-SCORM-Profile/pull/30
