### ISSUE TITLE
ADLnet paths result in 404 error

### ISSUE THREAD

**Issue by T1ckL35** [adlnet/xAPI-SCORM-Profile#33]
Hi,
I'm just looking at implementing various parts of the SCORM to xAPI process. Unfortunately when I set up learning locker and the wrappers that reference this I get 404 errors for any IRI referencing the following path (or subpaths):
http://adlnet.gov/xapi/profile
http://adlnet.gov/xapi/profile/scorm/activity-state
etc...

I can see that in April things were fine (I've found a cached page on google) but it is currently broken. Has this changed and does the document need to be updated?

Cheers
Simon

**Comment by creighton** [comment]
I think that activity-state one is just saying that there are no states for that activity, which is ok. As for the core IRI http://adlnet.gov/xapi/profile, we must have lost the profile during some website updates. I'll look for it. But that should not break anything. As far as I can remember all we were doing was hosting the JSON activity definition at that location. 
see: https://github.com/adlnet/SCORM-to-xAPI-Wrapper/blob/master/SCORMToXAPIFunctions.js#L669
and: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#metadata-requirements

It is a MAY. Technically speaking that IRI is just an identifier and does not need to resolve. If it does - like how it used to - it could contain the activity definition. But this is optional and should not break anything by no longer existing. If the http://adlnet.gov/xapi/profile IRI is causing some issue, please give me more details and I'll try to look into it.

**Comment by T1ckL35** [comment]
Apologies, this is a red herring. As a result of your information here and in this bug (where I list my problem/solution): https://github.com/adlnet/SCORM-to-xAPI-Wrapper/issues/4
I have been able to figure out the problem.

Thanks for pushing me in the right direction and for the quick response time, it is appreciated
Simon
