### ISSUE TITLE
How to detect if a scorm package already support xAPI

### ISSUE THREAD

**Issue by mahpah** [adlnet/xAPI-SCORM-Profile#53]
I'm trying to play some scorm package in my site and record user progress. I've found some scorm packages which can send tincan statement if played in a proper mode. But my problem is I don't know which package has this ability. Is some field in manifest provide this type of information? 
I'm new to this subject, sorry if this is a dumb question.

**Comment by jono-poltrack** [comment]
Hi mahpah.  Unfortunately, there is no (interoperable) means to discover if content in a SCORM package is able to send xAPI statements.  SCORM packages give the ability to describe two main types of resources Sharable Content Objects (SCOs) and assets -- content that communicates using SCORM and content that doesn't, respectively

There is no interoperable means to detect if something will communicate via xAPI.  That beings said, there is a possibility that the tool you are using generated some means to detect this, but it would be a vendor-specific thing.

**Comment by mahpah** [comment]
Thank you @jono-poltrack.
