### ISSUE TITLE
Add context activity (parent) for interactions

### ISSUE THREAD

**Issue by jonopoltrack** [adlnet/xAPI-SCORM-Profile#8]
in order to know that several interactions are in the same activity, add a context activity to identify the parent activity (which may differ from the course)

parents should be ordered so that last parent context activity is the activity that contains the interactions.

**Comment by creighton** [comment]
after debate it's been decided the best we can do is recommend that "known parents", such as a sco containing a test, should be used as 'parent' in contextActivities. Anything else is generally considered a 'grouping' activity. Pull request #30 includes these changes.
