### ISSUE TITLE
cmi interactions

### ISSUE THREAD

**Issue by jonopoltrack** [adlnet/xAPI-SCORM-Profile#9]
Best practice is to host the definition at the IRI.

In order to send the interaction type in the activity definition, you need to include blank arrays for items like "choices" if you don't want to send them with the statement.

Provide guidance on the best practice and how that affects what you must do in the statements.

**Comment by creighton** [comment]
pretty sure this was just an LRS issue for us. i think it's fixed. @jonopoltrack do you agree
